// TURN
export const INCREMENT = "INCREMENT";
// ENEMY
export const ENEMY_ATTACK = "ENEMY_ATTACK";
// PARTY & HEROES
export const PARTY_FIGHT = "PARTY_FIGHT";
export const PARTY_MAGIC = "PARTY_MAGIC";
export const PARTY_DRINK = "PARTY_DRINK";
export const PARTY_RUN = "PARTY_RUN";
export const PARTY_ITEM = "PARTY_ITEM";
export const MOVE_HERO = "MOVE_HERO";
// PHASE
export const UPDATE_PHASE = "UPDATE_PHASE";
// ABOUT TO SELECT SOMETHNG
export const SELECT_ACTION = "SELECT_ACTION";
// SELECTED SOMETHING
export const SELECTED_ENEMY = "SELECTED_ENEMY";
export const SELECTED_HERO = "SELECTED_HERO";
export const SELECTED_ACTION = "SELECTED_ACTION";
// REWARD SOMETHING
export const REWARD_EXPERIENCE = "REWARD_EXPERIENCE";
// INC
export const INC_HERO_ACTED_COUNT = "INC_HERO_ACTED_COUNT";
// BATTLE
export const BATTLE_BEGIN = "BATTLE_BEGIN";
export const BATTLE_PROGRESSING = "BATTLE_PROGRESSING";
export const BATTLE_END = "BATTLE_END";


